version: '3.9'

services:
  xidb:
    image: xi-db:main
    networks:
      xi-network:
        ipv4_address: 192.168.10.5
    expose:
      - "3306"
    volumes:
      - ${DB_MOUNT}:/var/lib/mysql
    restart: unless-stopped

  autobackup-xidb:
    image: selim13/automysqlbackup
    volumes:
      - ${DB_BACKUP}:/backup
    environment:
      DBHOST: "xidb"
      DBPORT: 3306
      DBNAMES: "all"
      USERNAME: "${DB_USER}"
      PASSWORD: "${DB_USER_PASSWD}"
      CRON_SCHEDULE: "0 0 * * *"
      CREATE_DATABASE: "no"
    networks:
      xi-network:
        ipv4_address: 192.168.10.4
    restart: unless-stopped

networks:
  xi-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
