import os
import subprocess

container = os.getenv('CONTAINER')
username = os.getenv('DB_USER')
password = os.getenv('DB_USER_PASSWD')
database = os.getenv('DB_NAME')

safe_files_to_load = [
    "sql/abilities.sql",
    "sql/abilities_charges.sql",
    "sql/augments.sql",
    "sql/automaton_abilities.sql",
    "sql/automaton_spells.sql",
    "sql/bcnm_battlefield.sql",
    "sql/bcnm_info.sql",
    "sql/bcnm_treasure_chests.sql",
    "sql/blue_spell_list.sql",
    "sql/blue_spell_mods.sql",
    "sql/blue_traits.sql",
    "sql/campaign_map.sql",
    "sql/campaign_nation.sql",
    "sql/cheat_types.sql",
    "sql/despoil_effects.sql",
    "sql/exp_base.sql",
    "sql/exp_table.sql",
    "sql/fishing_area.sql",
    "sql/fishing_bait.sql",
    "sql/fishing_bait_affinity.sql",
    "sql/fishing_catch.sql",
    "sql/fishing_fish.sql",
    "sql/fishing_group.sql",
    "sql/fishing_mob.sql",
    "sql/fishing_rod.sql",
    "sql/fishing_zone.sql",
    "sql/gardening_results.sql",
    "sql/guild_item_points.sql",
    "sql/guild_shops.sql",
    "sql/guilds.sql",
    "sql/instance_entities.sql",
    "sql/instance_list.sql",
    "sql/item_basic.sql",
    "sql/item_equipment.sql",
    "sql/item_furnishing.sql",
    "sql/item_latents.sql",
    "sql/item_mods.sql",
    "sql/item_mods_pet.sql",
    "sql/item_puppet.sql",
    "sql/item_usable.sql",
    "sql/item_weapon.sql",
    "sql/job_point_gifts.sql",
    "sql/job_points.sql",
    "sql/magian.sql",
    "sql/merits.sql",
    "sql/mob_droplist.sql",
    "sql/mob_family_mods.sql",
    "sql/mob_family_system.sql",
    "sql/mob_groups.sql",
    "sql/mob_pets.sql",
    "sql/mob_pool_mods.sql",
    "sql/mob_pools.sql",
    "sql/mob_resistances.sql",
    "sql/mob_skill_lists.sql",
    "sql/mob_skills.sql",
    "sql/mob_spawn_mods.sql",
    "sql/mob_spawn_points.sql",
    "sql/mob_spell_lists.sql",
    "sql/nm_spawn_points.sql",
    "sql/npc_list.sql",
    "sql/pet_list.sql",
    "sql/pet_name.sql",
    "sql/skill_caps.sql",
    "sql/skill_ranks.sql",
    "sql/skillchain_damage_modifiers.sql",
    "sql/spell_list.sql",
    "sql/status_effects.sql",
    "sql/synth_recipes.sql",
    "sql/traits.sql",
    "sql/transport.sql",
    "sql/triggers.sql",
    "sql/unity_system.sql",
    "sql/water_points.sql",
    "sql/weapon_skills.sql",
    "sql/zone_weather.sql",
    "sql/zonelines.sql",
    "sql/qr_sql/out_of_combat_effect.sql",
    "sql/qr_sql/black_mage_time_machine.sql",
    "sql/qr_sql/char_distribute_xp.sql",
    "sql/qr_sql/artifact_changes.sql",
    "sql/qr_sql/artifact_status_effects.sql",
    "sql/qr_sql/nexus_cape.sql",
    "sql/qr_sql/helm_gear_mods.sql",
    "sql/qr_sql/qr_augments.sql",
    "sql/qr_sql/beastman_bosses.sql",
    "sql/qr_sql/new_recipes.sql",
    "sql/qr_sql/qr_triggers.sql",
    "sql/qr_sql/trust_changes.sql",
    "sql/qr_sql/lowbie_nm_drops.sql",
    "sql/qr_sql/sky_drop_pools.sql",
    "sql/qr_sql/sea_drop_pools.sql",
    "sql/qr_sql/hnm_drop_pools.sql",
    "sql/qr_sql/hnm_stat_changes.sql",
    "sql/qr_sql/dynamis.sql",
    "sql/qr_sql/item_price_changes.sql",
    "sql/qr_sql/mid_nm_drops.sql",
    "sql/qr_sql/missing_recipes.sql",
]

for sql_file in safe_files_to_load:
    subprocess.run(
        f"docker exec -i {container} sh -c \"mysql -u {username} -p{password} {database}\" < {sql_file}",
        shell=True
    )

